Part1
Yam0r/Spring-Boot-intro pull request #1
Opened 2024-06-21 09:03 UTC by Yam0r

2024-06-22 11:17 UTC, Elena-Bruyako requested changes
Please, check the project structure. 
Need to fix some comments and implement the logic according to the HW

2024-06-22 11:17 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springintro/SpringIntroApplication.java
> +    }
You should implement task description
`Class with @SpringBootApplication annotation that will have a CommandLineRunner bean.`

2024-06-22 11:17 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springintro/repository/BookRepository.java
> +public interface BookRepository extends JpaRepository<Book, Long> {
Using JpaRepository related to another HW. 
Here you need to implement
```
BookRepository interface with methods and BookRepositoryImpl class:

Book save(Book book);
List findAll();
```

2024-06-22 11:17 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springintro/Book.java
> +@Entity
Add lombok dependency and use these annotations, instead of generating methods
```
@Getter
@Setter
```

2024-06-22 11:17 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springintro/repository/impl/BookServiceImpl.java
> +        return List.of();
you should implement the logic

2024-06-22 11:17 UTC, Elena-Bruyako commented on src/main/resources/application.properties
> +
```suggestion
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

```

2024-06-22 11:17 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springintro/Book.java
> +package mate.academy.springintro;
create `model` package and replace Book there

2024-06-22 11:17 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springintro/repository/BookService.java
> +package mate.academy.springintro.repository;
Service isn't related to repository package

2024-06-22 11:17 UTC, Elena-Bruyako commented on src/test/java/resources/application.properties
> +spring.datasource.url=jdbc:h2:mem:book
resources folder should be placed at `src/test/resources`, but you have `src/test/java/resources/`

2024-06-23 05:57 UTC, Elena-Bruyako requested changes
Please, fix comments. If you have some questions, ask in chat. Check learning materials and implement the logic

2024-06-23 05:57 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springintro/repository/impl/BookRepositoryImpl.java
> +        books.add(book);
You should add book to database

2024-06-23 05:57 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springintro/repository/impl/BookRepositoryImpl.java
> +        return new ArrayList<>(books);
the same

2024-06-23 05:57 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springintro/repository/impl/BookServiceImpl.java
> +
```suggestion
```

2024-06-23 05:57 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springintro/repository/BookService.java
> +package mate.academy.springintro.repository;
not fixed

2024-06-23 05:57 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springintro/SpringIntroApplication.java
> +    }
not fixed

2024-06-27 12:30 UTC, okuzan approved these changes

2024-06-27 12:30 UTC, okuzan commented on src/main/java/mate/academy/springintro/model/Book.java
> +
```suggestion
```

2024-06-27 12:30 UTC, okuzan commented on src/main/java/mate/academy/springintro/service/impl/BookServiceImpl.java
> +
```suggestion
```

2024-09-20 16:05 UTC, merged