feat ShoppingCart model
Yam0r/Spring-Boot-intro pull request #14
Opened 2024-11-25 00:24 UTC by Yam0r

2024-11-25 09:14 UTC, liliia-ponomarenko requested changes
Good job! Let’s  improve your solution;)

2024-11-25 09:14 UTC, liliia-ponomarenko commented on src/main/java/mate/academy/springintro/dto/shoppingcart/AddToCartRequestDto.java
> +
```suggestion
```

2024-11-25 09:14 UTC, liliia-ponomarenko commented on src/main/java/mate/academy/springintro/dto/shoppingcart/CartItemResponseDto.java
> +
```suggestion
```
Leave only one empty line at the end of the file

2024-11-25 09:14 UTC, liliia-ponomarenko commented on src/main/java/mate/academy/springintro/dto/shoppingcart/ShoppingCartResponseDto.java
> +    }
Redundant  constructor

2024-11-25 09:14 UTC, liliia-ponomarenko commented on src/main/java/mate/academy/springintro/model/CartItem.java
> +    @ManyToOne
use fetch type LAZY

2024-11-25 09:14 UTC, liliia-ponomarenko commented on src/main/java/mate/academy/springintro/model/CartItem.java
> +    @ManyToOne
```suggestion
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
```

2024-11-25 09:14 UTC, liliia-ponomarenko commented on src/main/java/mate/academy/springintro/model/CartItem.java
> +    @ManyToOne
the same

2024-11-25 09:14 UTC, liliia-ponomarenko commented on src/main/java/mate/academy/springintro/model/CartItem.java
> +    }
redundant constructor

2024-11-25 09:14 UTC, liliia-ponomarenko commented on src/main/java/mate/academy/springintro/model/CartItem.java
> +@RequiredArgsConstructor
why do you need this annotation?

2024-11-25 09:14 UTC, liliia-ponomarenko commented on src/main/java/mate/academy/springintro/security/CustomUserDetails.java
> +public class CustomUserDetails implements UserDetails {
Why do you need it? Let’s  implement it in the User entity

2024-11-25 09:14 UTC, liliia-ponomarenko commented on src/main/java/mate/academy/springintro/security/CustomUserDetails.java
> +        return true;
```suggestion
        return !isDeleted;
```

2024-11-25 09:14 UTC, liliia-ponomarenko commented on src/main/java/mate/academy/springintro/service/ShoppingCartService.java
> +
the same (fix it everywhere)

2024-11-25 09:14 UTC, liliia-ponomarenko commented on src/main/java/mate/academy/springintro/service/impl/ShoppingCartServiceImpl.java
> +
```suggestion
```

2024-11-25 09:14 UTC, liliia-ponomarenko commented on src/main/java/mate/academy/springintro/model/ShoppingCart.java
> +    @OneToOne
you can use MapsId

2024-11-25 09:14 UTC, liliia-ponomarenko commented on src/main/java/mate/academy/springintro/service/impl/ShoppingCartServiceImpl.java
> +        return new ShoppingCartResponseDto(shoppingCart);
What are you return? Let’s  use a mapper

2024-11-25 09:14 UTC, liliia-ponomarenko commented on src/main/java/mate/academy/springintro/service/impl/ShoppingCartServiceImpl.java
> +        book.setId(requestDto.getBookId());
get the book by ID from DB

2024-11-25 09:14 UTC, liliia-ponomarenko commented on src/main/java/mate/academy/springintro/service/impl/ShoppingCartServiceImpl.java
> +        return new ShoppingCartResponseDto(cartItem.getShoppingCart());
the same, use mapper

2024-11-25 09:14 UTC, liliia-ponomarenko commented on src/main/java/mate/academy/springintro/service/impl/ShoppingCartServiceImpl.java
> +    private ShoppingCart createShoppingCartForUser(User user) {
you should call this logic in the registration method

2024-11-25 09:14 UTC, liliia-ponomarenko commented on src/main/resources/db/changelog/changes/create-cart-items-table.yaml
> +            constraintName: fk_cart_items_book
add one empty line (check other files)

2024-11-25 09:14 UTC, liliia-ponomarenko commented on src/main/resources/db/changelog/db.changelog-master.yaml
> +#      file: db/changelog/changes/create-cart-items-table.yaml
uncomment new changesets

2024-11-27 08:09 UTC, liliia-ponomarenko requested changes
Good job! Let’s  fix your solution ;)

2024-11-27 08:09 UTC, liliia-ponomarenko commented on src/main/java/mate/academy/springintro/mapper/ShoppingCartMapper.java
> +
```suggestion
```

2024-11-27 08:09 UTC, liliia-ponomarenko commented on src/main/java/mate/academy/springintro/model/CartItem.java
> +
```suggestion
```
Only one empty line at the end of the file

2024-11-27 08:09 UTC, liliia-ponomarenko commented on src/main/java/mate/academy/springintro/service/impl/UserServiceImpl.java
> +
Why do you move ShoppingCart logic to UserService? Let’s  move it to the separate ShoppingCartService class

2024-11-27 08:09 UTC, liliia-ponomarenko commented on src/main/java/mate/academy/springintro/service/impl/UserServiceImpl.java
> +    }
use mapper

2024-11-27 08:09 UTC, liliia-ponomarenko commented on src/main/java/mate/academy/springintro/service/impl/UserServiceImpl.java
> +    }
the same

2024-11-27 08:09 UTC, liliia-ponomarenko commented on src/main/resources/db/changelog/db.changelog-master.yaml
> -
include new changesets to  changelog-master.yaml

2024-11-27 08:09 UTC, liliia-ponomarenko commented on src/main/java/mate/academy/springintro/model/ShoppingCart.java
> +    @OneToOne
not fixed

2024-11-27 13:10 UTC, Elena-Bruyako requested changes
see comments

2024-11-27 13:10 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springintro/controller/ShoppingCartController.java
> +    @GetMapping
add swagger annotations where are needed

2024-11-27 13:10 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springintro/dto/shoppingcart/AddToCartRequestDto.java
> +    @Min(1)
```suggestion
    @NotNull
    @Positive
    private Long bookId;

    @Positive
```

2024-11-27 13:10 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springintro/dto/shoppingcart/UpdateCartItemRequestDto.java
> +    @Min(1)
```suggestion
    @Positive
```

2024-11-27 13:10 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springintro/model/User.java
> +                .collect(Collectors.toList());
```suggestion
        return roles;
```

2024-11-27 13:10 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springintro/service/impl/ShoppingCartServiceImpl.java
> +                .orElseThrow(() -> new RuntimeException("Shopping Cart not found for user "
```suggestion
                .orElseThrow(() -> new EntityNotFoundException("Shopping Cart not found for user "
```

2024-11-27 13:10 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springintro/service/impl/ShoppingCartServiceImpl.java
> +                .orElseThrow(() -> new RuntimeException("User not found with id " + userId));
check other places

```suggestion
                .orElseThrow(() -> new EntityNotFoundException("User not found with id " + userId));
```

2024-11-27 13:10 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springintro/service/impl/ShoppingCartServiceImpl.java
> +    private ShoppingCart createShoppingCartForUser(User user) {
```suggestion
    @Override
    public ShoppingCart createShoppingCartForUser(User user) {
```

2024-11-27 13:10 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springintro/service/impl/UserServiceImpl.java
> +        shoppingCartRepository.save(shoppingCart);
```suggestion
        shoppingCartService.createShoppingCartForUser(user);
```

2024-11-27 13:10 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springintro/service/ShoppingCartService.java
> +    void removeCartItem(Long userId, Long cartItemId);
```suggestion
    void removeCartItem(Long userId, Long cartItemId);
    
    ShoppingCart createShoppingCartForUser(User user);
```

2024-11-27 13:10 UTC, Elena-Bruyako commented on src/main/resources/db/changelog/changes/create-shopping-carts-table.yaml
> +                  name: id
remove, you are using `@MapsId` in entity

2024-11-27 13:10 UTC, Elena-Bruyako commented on src/main/resources/db/changelog/changes/create-shopping-carts-table.yaml
> +                    unique: true
```suggestion
                  constraints:
                    primaryKey: true
                    nullable: false
```

2024-11-27 13:10 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springintro/model/ShoppingCart.java
> +    @GeneratedValue(strategy = GenerationType.IDENTITY)
```suggestion
```

2024-12-02 07:41 UTC, liliia-ponomarenko approved these changes
Good job! But fix my comments before merging ;)

2024-12-02 07:41 UTC, liliia-ponomarenko commented on src/main/java/mate/academy/springintro/service/impl/UserServiceImpl.java
> +        shoppingCartRepository.save(shoppingCart);
not fixed

2024-12-02 07:41 UTC, liliia-ponomarenko commented on src/main/java/mate/academy/springintro/service/impl/UserServiceImpl.java
> +
```suggestion
```
Leave only one empty line

2024-12-02 07:41 UTC, liliia-ponomarenko commented on src/main/resources/db/changelog/changes/create-shopping-carts-table.yaml
> +                  autoIncrement: true
using MapsId you can have only one column `id` or `user_id`

2024-12-08 13:57 UTC, merged