add Dockerfile
Yam0r/Spring-Boot-intro pull request #15
Opened 2024-12-01 15:58 UTC by Yam0r

2024-12-02 07:53 UTC, liliia-ponomarenko requested changes
Good job! Let’s  improve your solution ;)

2024-12-02 07:53 UTC, liliia-ponomarenko commented on .env
> +DEBUG_PORT=5005
Don’t push the `.env` file with sensitive data. better create `.env.templete`.
Let’s add `.env` to `.gitignore`

2024-12-02 07:53 UTC, liliia-ponomarenko commented on docker-compose.yml
> +    ports:
Let’s  use MySQL in your setups

2024-12-02 07:53 UTC, liliia-ponomarenko commented on docker-compose.yml
> +      - "5433:5423"
use variables

2024-12-02 07:53 UTC, liliia-ponomarenko commented on docker-compose.yml
> +      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
the same use variable for the debug port value

2024-12-02 07:53 UTC, liliia-ponomarenko commented on pom.xml
> +		</dependency>
so which DB do you use?

2024-12-02 07:53 UTC, liliia-ponomarenko commented on src/main/resources/db/changelog/db.changelog-master.yaml
> +#      file: db/changelog/changes/set-bcrypt-password.yaml
Let’s  uncomment changesets

2024-12-08 11:18 UTC, okuzan requested changes

2024-12-08 11:18 UTC, okuzan commented on .env
> +MYSQL_ROOT_PASSWORD=root
```suggestion
MYSQL_ROOT_PASSWORD=
```

2024-12-08 11:18 UTC, okuzan commented on .env
> +MYSQL_ROOT_PASSWORD=root
not fixed, push .env.template here with actual values removed
use git rm --cached .env to remove .env from remote while keeping it locally, and ensure it's not committed again by adding it to .gitignore

2024-12-08 11:18 UTC, okuzan commented on docker-compose.yml
> +      - "3307:3306"
not fixed, use ${ENV_VARIABLES} for ports, same for debug port at the last line

2024-12-09 08:52 UTC, liliia-ponomarenko approved these changes
Good job! Minor comment

2024-12-09 08:52 UTC, liliia-ponomarenko commented on docker-compose.yml
> +      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8080"
you can use DEBUG_PORT variable

2024-12-09 13:40 UTC, merged