Add order model
Yam0r/Spring-Boot-intro pull request #16
Opened 2024-12-08 16:34 UTC by Yam0r

2024-12-09 14:04 UTC, Elena-Bruyako requested changes
resolve branch conflicts first

2024-12-10 12:01 UTC, JJJazl requested changes

2024-12-10 12:01 UTC, JJJazl commented on src/main/java/mate/academy/springintro/config/OrderMapper.java
> +public class OrderMapper {
Move the logic of creating an order to the service class and add method `toDto` here. Implement this mapper like the others. 
By the way, it's a bad practice to load a data from the DB in the mapper.

2024-12-10 12:01 UTC, JJJazl commented on src/main/java/mate/academy/springintro/controller/OrderController.java
> +        return ResponseEntity.status(HttpStatus.CREATED).body(order);
Something strange happens here)
```suggestion
        User user = (User) authentication.getPrincipal();
        OrderResponseDto orderResponseDto = orderService.placeOrder(user, orderRequestDto);
        return ResponseEntity.status(HttpStatus.CREATED).body(orderResponseDto);
```

2024-12-10 12:01 UTC, JJJazl commented on src/main/java/mate/academy/springintro/controller/OrderController.java
> +    public ResponseEntity<List<Order>> getOrderHistory(Authentication authentication,
Same here. We need to have all the logic at the service layer + return a DTO object to the client, not an entity

2024-12-10 12:01 UTC, JJJazl commented on src/main/java/mate/academy/springintro/controller/OrderController.java
> +    public ResponseEntity<Order> placeOrder(@RequestBody @Valid OrderRequestDto orderRequestDto,
```suggestion
    public ResponseEntity<OrderResponseDto> placeOrder(@RequestBody @Valid OrderRequestDto orderRequestDto,
```

2024-12-10 12:01 UTC, JJJazl commented on src/main/java/mate/academy/springintro/controller/OrderController.java
> +    }
```suggestion
```

2024-12-10 12:01 UTC, JJJazl commented on src/main/java/mate/academy/springintro/controller/OrderController.java
> +    public ResponseEntity<Order> updateOrderStatus(@PathVariable Long id,
Same

2024-12-10 12:01 UTC, JJJazl commented on src/main/java/mate/academy/springintro/model/Order.java
> +    @ManyToOne
```suggestion
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
```

2024-12-10 12:01 UTC, JJJazl commented on src/main/java/mate/academy/springintro/model/OrderItem.java
> +    @ManyToOne
Same here

2024-12-10 12:01 UTC, JJJazl commented on src/main/java/mate/academy/springintro/model/OrderItem.java
> +    @ManyToOne
Same here

2024-12-10 12:01 UTC, JJJazl commented on src/main/java/mate/academy/springintro/model/OrderItem.java
> +public class OrderItem {
In `Order` you have `Set<OrderItem>`, but you didn't override `equals()` and `hashCode()` methods. It potentially can cause bugs.
Here are 2 articles on how to do this (we need to use the approach like in the second one):
https://vladmihalcea.com/hibernate-facts-equals-and-hashcode/
https://vladmihalcea.com/how-to-implement-equals-and-hashcode-using-the-jpa-entity-identifier

2024-12-10 12:01 UTC, JJJazl commented on src/main/java/mate/academy/springintro/service/UserService.java
> +    User findById(Long id);
You can pass a `User` from the controller
```suggestion
```

2024-12-10 12:01 UTC, JJJazl commented on src/main/java/mate/academy/springintro/service/OrderService.java
> +public interface OrderService {
You have to return DTOs, not entites

2024-12-10 12:01 UTC, JJJazl commented on src/main/java/mate/academy/springintro/service/impl/OrderServiceImpl.java
> +        return orderRepository.save(order);
This method should be completely rewritten, let's discuss it in the chat or Q&A session if you will have questions

2024-12-12 17:07 UTC, Elena-Bruyako requested changes
see comments

2024-12-12 17:07 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springintro/controller/OrderController.java
> +    private Long getUserIdFromAuthentication(Authentication authentication) {
it looks like unused method

2024-12-12 17:07 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springintro/controller/OrderController.java
> +    private Set<OrderItem> getOrderItemsFromRequest(OrderRequestDto orderRequestDto) {
remove unused method

2024-12-15 15:25 UTC, sarakhmen approved these changes
lgtm!

2024-12-15 16:20 UTC, merged