Spring boot data jpa
Yam0r/Spring-Boot-intro pull request #2
Opened 2024-07-03 13:59 UTC by Yam0r

2024-07-04 06:18 UTC, Elena-Bruyako requested changes
Let's stick to the task description:

Add Liquibase support
Change spring.jpa.hibernate.ddl-auto property value to validate
Implement soft delete concept for the Book entity
Add missing endpoints and methods for BookService

2024-07-04 06:18 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springintro/service/BookRepository.java
> +    Book save(Book book);
remove methods

2024-07-04 06:18 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springintro/service/impl/BookRepositoryImpl.java
> +public abstract class BookRepositoryImpl implements BookRepository {
remove class

2024-07-04 06:18 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springintro/service/impl/BookServiceImpl.java
> +@Service
```suggestion
@Service
@RequiredArgsConstructor
```

2024-07-04 06:18 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springintro/service/impl/BookServiceImpl.java
> +
```suggestion
```

2024-07-04 06:18 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springintro/service/impl/BookServiceImpl.java
> +    public BookServiceImpl(BookRepository bookRepository) {
remove constructor

2024-07-04 06:18 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springintro/service/BookRepository.java
> +package mate.academy.springintro.service;
```suggestion
package mate.academy.springintro.repository;
```

2024-07-04 06:18 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springintro/SpringIntroApplication.java
> +    public void run(String... args) throws Exception {
remove

2024-07-04 06:18 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springintro/SpringIntroApplication.java
> +    private BookService bookService;
```suggestion
```

2024-07-04 06:18 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springintro/SpringIntroApplication.java
> +public class SpringIntroApplication implements CommandLineRunner {
Where is your controller with task implementation?

Book Endpoints:

GET: /api/books (Retrieve book catalog) (should be done in the previous PR)
GET: /api/books/{id} (Retrieve book details) (should be done in the previous PR)
POST: /api/books (Create a new book) (should be done in the previous PR)
PUT: /api/books/{id} (Update a specific book)

2024-07-04 06:18 UTC, Elena-Bruyako commented on src/main/resources/application.properties
> +spring.jpa.hibernate.ddl-auto=update
```suggestion
spring.jpa.hibernate.ddl-auto=validate
```

2024-07-04 06:18 UTC, Elena-Bruyako commented on src/test/java/mate/academy/springintro/SpringIntroApplicationTests.java
> +public class SpringIntroApplicationTests {
```suggestion
@SpringBootTest
public class SpringIntroApplicationTests {
```

2024-07-04 06:18 UTC, Elena-Bruyako commented on src/test/java/mate/academy/springintro/SpringIntroApplicationTests.java
> +
```
@Test
    void contextLoads() {
    }
```

2024-07-05 12:34 UTC, Elena-Bruyako requested changes
Please, don't send new HW if you don't finish previous one. You have two open PRs with mistakes that should be fixed.

2024-07-20 11:16 UTC, Elena-Bruyako requested changes
see pr

2024-07-20 11:16 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springintro/controller/BookController.java
> +@RestController
```suggestion
@RestController
@RequiredArgsConstructor
```

2024-07-20 11:16 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springintro/controller/BookController.java
> +    public BookController(BookService bookService) {
remove

2024-07-20 11:16 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springintro/controller/BookController.java
> +@RequestMapping("/api/books")
```suggestion
@RequestMapping("/books")
```

add `server.servlet.context-path=/api` to application.properties

2024-07-20 11:16 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springintro/controller/BookController.java
> +        Optional<Book> book = bookService.findById(id);
```suggestion
        return bookService.findById(id);
```

2024-07-20 11:16 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springintro/controller/BookController.java
> +    public ResponseEntity<Book> findById(@PathVariable Long id) {
```suggestion
    public BookDto findById(@PathVariable Long id) {
```

2024-07-20 11:16 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springintro/controller/BookController.java
> +    public List<Book> findAll() {
```suggestion
    public List<BookDto> findAll() {
```

2024-07-20 11:16 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springintro/controller/BookController.java
> +    public Book create(@RequestBody Book book) {
```suggestion
    public BookDto create(@RequestBody CreateBookRequestDto book) {
```

2024-07-20 11:16 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springintro/controller/BookController.java
> +    public ResponseEntity<Book> update(@PathVariable Long id, @RequestBody Book book) {
```suggestion
    public BookDto update(@PathVariable Long id, @RequestBody CreateBookRequestDto book) {
```

2024-07-20 11:16 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springintro/controller/BookController.java
> +        return bookService.findById(id)
```suggestion
        return bookService.updateBook(id, book);
```

2024-07-20 11:16 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springintro/controller/BookController.java
> +    public ResponseEntity<Void> delete(@PathVariable Long id) {
```suggestion
    public void delete(@PathVariable Long id) {
```

2024-07-20 11:16 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springintro/controller/BookController.java
> +        bookService.delete(id);
```suggestion
        bookService.deleteById(id);
```

2024-07-20 11:16 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springintro/model/Book.java
> +    @Column(name = "description", columnDefinition = "TEXT")
```suggestion
```

2024-07-20 11:16 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springintro/model/Book.java
> +    private Boolean deleted = false;
```suggestion
    private boolean isDeleted = false;
```

2024-07-20 11:16 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springintro/repository/BookRepository.java
> +    List<Book> findByDeletedFalse();
```suggestion
```

2024-07-20 11:16 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springintro/repository/BookRepository.java
> +    Optional<Book> findByIdAndDeletedFalse(Long id);
```suggestion
```

2024-07-20 11:16 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springintro/service/impl/BookServiceImpl.java
> +    public BookServiceImpl(BookRepository bookRepository) {
not fixed

2024-07-20 11:16 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springintro/model/Book.java
> +@Setter
```suggestion
@SQLDelete
@SQLResrtiction 
```

???

2024-07-20 11:16 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springintro/repository/BookService.java
> +package mate.academy.springintro.repository;
```suggestion
package mate.academy.springintro.service;
```

2024-07-20 11:16 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springintro/service/impl/BookServiceImpl.java
> +    public Book save(Book book) {
```suggestion
    public BookDto save(Book book) {
```
use Mapper

2024-07-20 11:16 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springintro/service/impl/BookServiceImpl.java
> +        return bookRepository.findByDeletedFalse();
bookRepository.findAll
use mapper

2024-07-20 11:16 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springintro/service/impl/BookServiceImpl.java
> +    public Optional<Book> findById(Long id) {
```suggestion
    public BookDto findById(Long id) {
    find or throw an exception
    use mapper
```

2024-07-20 11:16 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springintro/service/impl/BookServiceImpl.java
> +        bookRepository.findById(id).ifPresent(book -> {
```suggestion
        bookRepository.deleteById(id);
```

2024-07-20 11:16 UTC, Elena-Bruyako commented on src/main/resources/db/changelog/changes/creates-book-table.yaml
> +                  name: deleted
```suggestion
                  name: is_deleted
```

2024-07-25 09:56 UTC, okuzan requested changes

2024-07-25 09:56 UTC, okuzan commented on src/main/java/mate/academy/springintro/controller/BookController.java
> +                    existingBook.setCoverImage(book.getCoverImage());
that should be done in mapper

2024-08-05 14:45 UTC, Elena-Bruyako requested changes
Fix previous comments.

2024-08-05 14:45 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springintro/controller/BookController.java
> +        return bookService.findById(id)
not fixed

2024-08-05 14:45 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springintro/service/impl/BookServiceImpl.java
> +    private final BookRepository bookRepository; // Внедрение репозитория
remove comment

2024-08-05 14:45 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springintro/service/impl/BookServiceImpl.java
> +        bookRepository.findById(id).ifPresent(book -> {
not fixed

2024-08-05 14:45 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springintro/model/BookMapper.java
> +    public BookDto toEntity(BookRequestDto dto) {
read about MapStruct and how it works

2024-08-05 14:45 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springintro/model/BookDto.java
> +public class BookDto {
This is not DTO, it's entity

2024-08-05 14:45 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springintro/controller/BookController.java
> +    }
```suggestion
    public void deleteById(@PathVariable Long id) {
        bookService.deleteById(id);
    }
```

2024-08-05 14:45 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springintro/controller/BookController.java
> +        return bookService.findById(id)
```suggestion
    public BookDto updateBook(@PathVariable Long id,
                              @RequestBody CreateBookRequestDto book) {
        return bookService.updateBook(id, book);
    }
```

2024-08-05 14:45 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springintro/controller/BookController.java
> +    public BookDto create(@RequestBody BookDto book) {
```suggestion
    public BookDto create(@RequestBody CreateBookRequestDto book) {
```

2024-08-05 14:45 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springintro/controller/BookController.java
> +                .orElse(ResponseEntity.notFound().build());
```suggestion
    public BookDto getBookById(@PathVariable Long id) {
        return bookService.findById(id);
    }
```

2024-08-05 14:45 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springintro/controller/BookController.java
> +    public ResponseEntity<BookDto> update(@PathVariable Long id, @RequestBody BookDto book) {
```suggestion
    public ResponseEntity<BookDto> update(@PathVariable Long id, @RequestBody CreateBookRequestDto book) {
```

2024-08-06 08:41 UTC, Elena-Bruyako requested changes
Let's discuss you HW in chat.

2024-08-06 19:01 UTC, sarakhmen approved these changes

2024-09-19 13:02 UTC, Elena-Bruyako requested changes
there are not fix comment and changes from previous HW, provide PR with only search HW

2024-09-20 16:05 UTC, merged