SearchByCriteria
Yam0r/Spring-Boot-intro pull request #3
Opened 2024-09-20 16:32 UTC by Yam0r

2024-09-28 07:26 UTC, Elena-Bruyako requested changes
<img width="934" alt="Screenshot 2024-09-28 at 10 26 06" src="https://github.com/user-attachments/assets/b34bb4d6-cce0-4fea-bb4a-532ace846e09">
Branch still has conflicts, fix them first

2024-09-29 16:59 UTC, Elena-Bruyako requested changes
Why it looks like you already merged Search books HW ?

2024-09-29 16:59 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springintro/dto/BookDto.java
> +
remove empty line

2024-09-29 16:59 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springintro/dto/CreateBookRequestDto.java
> -
Use `@NotBlank` for String

2024-09-29 16:59 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springintro/exception/EntityNotFoundException.java
> +    public EntityNotFoundException(
```suggestion
    public EntityNotFoundException(String message) {
```

2024-09-29 16:59 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springintro/repository/SpecificationProvider.java
> +    Specification<T> getSpecification(
```suggestion
    Specification<T> getSpecification(String[] params);
```

2024-09-29 16:59 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springintro/repository/SpecificationProviderManager.java
> +    SpecificationProvider<T> getSpecificationProvider(
```suggestion
    SpecificationProvider<T> getSpecificationProvider(String key);
```

2024-09-29 16:59 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springintro/repository/book/BookSpecificationBuilder.java
>              spec = spec.and(bookSpecificationProviderManager.getSpecificationProvider("author")
create constants for String "author" etc

2024-09-29 16:59 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springintro/repository/book/spec/AuthorSpecificationProvider.java
> +                criteriaBuilder) -> root.get("author")
create constant for "author"

2024-09-29 16:59 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springintro/repository/book/spec/PriceSpecificationProvider.java
> +                criteriaBuilder) -> root.get("price")
create constant for "price"

2024-09-30 08:11 UTC, liliia-ponomarenko requested changes
Good job! Let's fix a few mistakes ;)

2024-09-30 08:11 UTC, liliia-ponomarenko commented on src/main/java/mate/academy/springintro/repository/book/BookSpecificationBuilder.java
> +    private final String priceMessage = "price";
Let's use constant formatting 
`private static final String AUTHOR_PARAMETER = "author";`

2024-09-30 08:11 UTC, liliia-ponomarenko commented on src/main/java/mate/academy/springintro/repository/book/BookSpecificationBuilder.java
> +
Only one empty line at the end of the file ;)

2024-09-30 08:11 UTC, liliia-ponomarenko commented on src/main/java/mate/academy/springintro/repository/book/spec/AuthorSpecificationProvider.java
> +    private final String authorMessage = "author";
the same, use constant format

2024-09-30 08:11 UTC, liliia-ponomarenko commented on src/main/java/mate/academy/springintro/repository/book/spec/PriceSpecificationProvider.java
> +    private final String priceMessage = "price";
the same

2024-09-30 08:11 UTC, liliia-ponomarenko commented on src/main/java/mate/academy/springintro/service/BookService.java
> -
Why do you remove this method?

2024-09-30 12:48 UTC, Elena-Bruyako requested changes

2024-09-30 12:48 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springintro/repository/book/spec/AuthorSpecificationProvider.java
> +    private static final String PRICE_PARAMETER = "price";
copy-paste, be attentive - `root.get("author")`

2024-09-30 12:48 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springintro/controller/BookController.java
> -    public void updateBookById(@PathVariable Long id,
why did you delete this endpoint?

2024-09-30 12:48 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springintro/repository/book/BookSpecificationProviderManager.java
> +
don't add empty line after class / method declaration

2024-10-01 12:23 UTC, Elena-Bruyako approved these changes

2024-10-06 10:18 UTC, closed without merging