deleted_unnecessary
Yam0r/Spring-Boot-intro pull request #4
Opened 2024-09-28 10:58 UTC by Yam0r

2024-10-06 12:06 UTC, Elena-Bruyako requested changes
Why GlobalExceptionHandler is already merged? 
You should provide request with particular HW, delete classes is bad approach

2024-10-06 12:06 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springintro/dto/CreateBookRequestDto.java
> +    @NotBlank
```suggestion
    @NotNull
```

2024-10-06 12:06 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springintro/dto/CreateBookRequestDto.java
> +    @NotNull
```suggestion
```

2024-10-06 12:06 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springintro/dto/CreateBookRequestDto.java
> +    @NotBlank
```suggestion
```

2024-10-08 12:20 UTC, Elena-Bruyako requested changes
Don't approve the HW that already merged in main.
Also, the name of Book table should be books not bookshop
Use Lombok annotations instead of generating constructors
There is a mess in PRs so it's better to join QnA session

2024-10-08 12:20 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springintro/dto/CreateBookRequestDto.java
> +    @NotBlank
remove annotation

2024-10-10 07:54 UTC, JJJazl commented
Agree with @Elena-Bruyako, will be better to join Q&A session and discuss the task and how to fix this issue. You can also write to your coordinator about it
Don't get upset, we will help you, so you can easily continue your learning journey!)

2024-10-12 14:43 UTC, sarakhmen approved these changes
This pr is approved so please merge it and follow discussed flow further:
- update main branch locally
- create new branch for your homework from the main branch
- add your homework specific changes only and create new PR

2024-10-12 14:44 UTC, merged